"""Ajout du don.

Revision ID: 003990771ba1
Revises: 7dd8599b6802
Create Date: 2024-05-15 12:18:51.192062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '003990771ba1'
down_revision = '7dd8599b6802'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('identifiant', sa.String(length=255), nullable=False),
    sa.Column('telephone', sa.String(length=10), nullable=False),
    sa.Column('modePayement', sa.String(length=10), nullable=False),
    sa.Column('projet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['projet_id'], ['projet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dons')
    # ### end Alembic commands ###
