"""Initial migration.

Revision ID: 47175ffb7a3f
Revises: 
Create Date: 2024-03-20 11:19:14.033329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47175ffb7a3f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorie', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
